spring:
  application:
    name: ef-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 192.168.150.105:8848 # Nacos地址
        namespace: easyfun_dev
        file-extension: yaml
        username: nacos
        password: 12345678
  config:
    import:
      - optional:nacos:ef-custom
      - optional:nacos:ef-gateway
      - optional:nacos:ef-gateway-${spring.profiles.active}
      - optional:nacos:ef-nacos
      - optional:nacos:ef-mysql
      - optional:nacos:ef-redis
      - optional:nacos:ef-jackson
      - optional:nacos:ef-jwt